### ISSUE TITLE
Data always exported as "cont" (continuous)?

### ISSUE THREAD

**Issue by ellisifnygaard** [jromanowska/HaplinMethyl#15]
I don't have time to look into this myself (especially since I won't be handling categorical env data any time soon), but I just wanted to make a note of this before I forget:

#### Some of the functions should probably be reviewed/tested in terms of how the `"cont"` status gets assigned to data that is later exported. 

In envDataRead.R, this

https://github.com/jromanowska/HaplinMethyl/blob/159f19a50bea17a91d1f4d6500104afc920b466f/R/envDataRead.R#L205

takes place *before*  this: 
https://github.com/jromanowska/HaplinMethyl/blob/159f19a50bea17a91d1f4d6500104afc920b466f/R/envDataRead.R#L210-L218

I might be missing something, but it looks like the exported data will be regarded as having "cont" status no matter whether `cont` is `TRUE` or `FALSE`. This also appears to be the case in [envDataSubset.R](https://github.com/jromanowska/HaplinMethyl/blob/master/R/envDataSubset.R):
https://github.com/jromanowska/HaplinMethyl/blob/159f19a50bea17a91d1f4d6500104afc920b466f/R/envDataSubset.R#L242-L248
(`	save.list <- c(cur.names, "cont.data")` *is not inside an `if`  statement; it appears to happen no matter what*) 
  
The same goes for [envDataReadFromObj.R](https://github.com/jromanowska/HaplinMethyl/blob/master/R/envDataReadFromObj.R):  
https://github.com/jromanowska/HaplinMethyl/blob/159f19a50bea17a91d1f4d6500104afc920b466f/R/envDataReadFromObj.R#L103-L116

It looks "buggy" to me , but  it might be fine 👀 Hard to say without testing 🕵️

**Comment by jromanowska** [comment]
The statement `save.list <- c(save.list, "cont")` creates the list with names of objects that will be saved in the .ffData/.RData files. Thus, the `cont` object will be saved, showing whether there is continuous data (`TRUE`) or categorical (`FALSE`). When you read in the .ffData/.RData files, you can check then whether object `cont == TRUE`.

The statements within the `if(cont)` are so that the class of the final object returned to the user is set accordingly to whether it's a continuous data (`cont == TRUE`) or not (`cont == FALSE`).

If it's still not clear, we can talk about it - maybe I can't explain it correctly in writing.
