### ISSUE TITLE
Clearer documentation for users who want to convert DNAm data to ffdata + RData fileset

### ISSUE THREAD

**Issue by ellisifnygaard** [jromanowska/HaplinMethyl#22]
When revisiting the documentation of `envDataRead` and `envDataReadFromObj` with new users of HaplinMethyl and Haplin in mind, who may have DNAm data in file formats other than `.ffData` + `.RData` filesets, I found the documentation a little unclear in some areas.
  
#### 1
Even after reading the documentation for `genDataRead`, I found this unclear:
https://github.com/jromanowska/HaplinMethyl/blob/d9fa31dd26c7b98d82320ba7456d86198b2f7529/R/envDataRead.R#L3-L4

There is no explicit mention of environmental data in the `genDataRead` documentation. Is it the `cov.data` matrix?

#### 2

This is a little confusing as it contradicts that all you need is a matrix in the memory:
https://github.com/jromanowska/HaplinMethyl/blob/d9fa31dd26c7b98d82320ba7456d86198b2f7529/R/envDataReadFromObj.R#L3-L4

Based on the documentation, I would assume that the simplest way to convert DNAm data from an arbitrary format to `env.data` /  `.ffData` + `.RData` is to load the data into memory and then convert it using `envDataReadFromObj`. Is this correct? 
If one has HM450K or EPIC data on a large population, this could be very time consuming or cause R to crash on a lot of computers. Is there another way?

**Comment by jromanowska** [comment]
Hi, Ellisif! Great to hear that you're still on track! :)

**1** I don't understand - why should `genDataRead` mention environmental data? `envDataRead` is for environmental data, while `genDataRead` is for gen data. The `cov.data` matrix has family information and covariates.

**2** This sentence was wrongly copied from `envDataRead` - please revise.

> Based on the documentation, I would assume that the simplest way to convert DNAm data from an arbitrary format to env.data / .ffData + .RData is to load the data into memory and then convert it using envDataReadFromObj. Is this correct?
>
> If one has HM450K or EPIC data on a large population, this could be very time consuming or cause R to crash on a lot of computers. Is there another way?

Do you mean here that loading the entire DNAm dataset could crash one's PC? There's always this possibility, yes... But that's why I've implemented this as ff-files - best is to use `envDataRead` function, to read a DNAm dataset from a file on the disk and transform it to an ff-matrix, which doesn't take as much memory.
